projeto/core/urls.py
from django.urls import path
from projeto.core import views as v

app_name = "core"

urlpatterns = [
    path("", v.index, name="index"),
]

projeto/estoque/urls.py
from django.urls import path
from django.urls.conf import include
from projeto.estoque import views as v

app_name = "estoque"

entrada_patterns = [
    path("", v.EstoqueEntradaList.as_view(), name="estoque_entrada_list"),
    path("add/", v.estoque_entrada_add, name="estoque_entrada_add"),
]

saida_patterns = [
    path("/", v.EstoqueSaidaList.as_view(), name="estoque_saida_list"),
    path("add/", v.estoque_saida_add, name="estoque_saida_add"),
]

urlpatterns = [
    path("<int:pk>/", v.EstoqueDetail.as_view(), name="estoque_detail"),
    path("entrada/", include(entrada_patterns)),
    path("saida/", include(saida_patterns)),
]

projeto/produto/urls.py
from django.urls import path
from projeto.produto import views as v

app_name = "produto"

urlpatterns = [
    path("", v.produto_list, name="produto_list"),
    path("<int:pk>/", v.produto_detail, name="produto_detail"),
    path("add/", v.ProdutoCreate.as_view(), name="produto_add"),
    path("<int:pk>/edit/", v.ProdutoUpdate.as_view(), name="produto_edit"),
    path("<int:pk>/json/", v.produto_json, name="produto_json"),
]

projeto/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path

urlpatterns = [
    path("", include("projeto.core.urls")),
    path("produto/", include("projeto.produto.urls")),
    path("estoque/", include("projeto.estoque.urls")),
    path("admin/", admin.site.urls),
    path("logout/", LogoutView.as_view(), name="logout"),
]

projeto/core/models.py
from django.db import models


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        "criado em",
        auto_now_add=True,
        auto_now=False,
    )
    modified = models.DateTimeField(
        "modificado em",
        auto_now_add=False,
        auto_now=True,
    )

    class Meta:
        abstract = True

projeto/core/views.py
from django.shortcuts import render


def index(request):
    return render(request, "index.html")

projeto/core/templates/includes/nav.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="#">Estoque</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
        aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'produto:produto_list' %}">Produtos</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">Estoque</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="{% url 'estoque:estoque_entrada_list' %}">Entrada</a>
                    <a class="dropdown-item" href="{% url 'estoque:estoque_saida_list' %}">Saída</a>
                </div>
            </li>
        </ul>
        {% if user.is_authenticated %}
        <ul class="navbar-nav px-3">
            <li class="nac-item text-nowrap">
                <a href="{% url 'logout' %}" class="nav-link">Sair</a>
            </li>
        </ul>
        {% else %}

        {% endif %}

    </div>
</nav>