projeto/produto/urls.py
from django.urls import path
from projeto.produto import views as v

app_name = "produto"

urlpatterns = [
    path("", v.produto_list, name="produto_list"),
    path("<int:pk>/", v.produto_detail, name="produto_detail"),
    path("add/", v.ProdutoCreate.as_view(), name="produto_add"),
    path("<int:pk>/edit/", v.ProdutoUpdate.as_view(), name="produto_edit"),
    path("<int:pk>/json/", v.produto_json, name="produto_json"),
]

projeto/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path

urlpatterns = [
    path("", include("projeto.core.urls")),
    path("produto/", include("projeto.produto.urls")),
    path("estoque/", include("projeto.estoque.urls")),
    path("admin/", admin.site.urls),
    path("logout/", LogoutView.as_view(), name="logout"),
]

projeto/produto/models.py
from django.db import models
from django.urls import reverse_lazy


class Produto(models.Model):
    importado = models.BooleanField(default=False)
    ncm = models.CharField("NCM", max_length=50)
    produto = models.CharField(max_length=100, unique=True)
    preco = models.DecimalField("preco", max_digits=7, decimal_places=2)
    estoque = models.IntegerField("estoque atual")
    estoque_minimo = models.PositiveIntegerField("estoque mínimo", default=0)

    class Meta:
        ordering = ("produto",)

    def __str__(self):
        return self.produto

    def get_absolute_url(self):
        return reverse_lazy("produto:produto_detail", kwargs={"pk": self.pk})

    def to_dict_json(self):
        return {
            "pk": self.pk,
            "produto": self.produto,
            "estoque": self.estoque,
        }

projeto/produto/forms.py
from django import forms

from .models import Produto


class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = "__all__"

projeto/produto/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView

from .forms import ProdutoForm
from .models import Produto


def produto_list(request):
    template_name = "produto_list.html"
    objects = Produto.objects.all()
    context = {"object_list": objects}
    return render(request, template_name, context)


def produto_detail(request, pk):
    template_name = "produto_detail.html"
    obj = Produto.objects.get(pk=pk)
    context = {"object": obj}
    return render(request, template_name, context)


def produto_add(request):
    template_name = "produto_form.html"
    return render(request, template_name)


class ProdutoCreate(CreateView):
    model = Produto
    template_name = "produto_form.html"
    form_class = ProdutoForm


class ProdutoUpdate(UpdateView):
    model = Produto
    template_name = "produto_form.html"
    form_class = ProdutoForm


def produto_json(request, pk):
    """Retorna o produto, id e e estoque"""
    produto = Produto.objects.filter(pk=pk)
    data = [item.to_dict_json() for item in produto]
    return JsonResponse({"data": data})

projeto/produto/templates/produto_detail.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'produto:produto_list' %}">Voltar</a>

<h1>
    {{ object }}
    <span class="pull-right">
        <a href="{% url 'produto:produto_edit' object.pk %}">
            <button type="button" class="btn btn-success">
                <span class="fa fa-pencil"></span>Editar
            </button>
        </a>
    </span>
</h1>
<div class="col-sm-6">
    <table class="table table-user-information">
        <tbody>
            <tr>
                <th class="text-right">Importado</th>
                <td>
                    {% if object.importado %}
                    <i class="fa fa-check-circle ok"></i>
                    {% else %}
                    <i class="fa fa-minus-circle no"></i>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th class="text-right">NCM</th>
                <td>{{ object.ncm }}</td>
            </tr>
            <tr>
                <th class="text-right">Preço</th>
                <td>R$ {{ object.preco }}</td>
            </tr>
            <tr>
                <th class="text-right">Estoque</th>
                <td>{{ object.estoque }}</td>
            </tr>
            <tr>
                <th class="text-right">Estoque Mínimo</th>
                <td>{{ object.estoque_minimo }}</td>
            </tr>
        </tbody>
    </table>
</div>
{% endblock content %}

projeto/produto/templates/produto_form.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}
<form method="POST" novalidate>
    {% csrf_token %}
    {% for field in form.visible_fields %}
    <div class="form-group{% if field.errors %} has-error {% endif %}">
        <label for="{{ field.id_for_label }}">
            {% if field.field.required %}
            <span class="required">{{ field.label }} </span>
            {% else %}
            {{ field.label }}
            {% endif %}
        </label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
        <span class="text-muted">{{ error }}</span>
        {% endfor %}
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-success">Cadastrar</button>
</form>


{% endblock content %}

{% block js %}
<script src="{% static 'js/produto.js' %}"></script>
{% endblock js %}

projeto/produto/templates/produto_list.html
{% extends "base.html" %}

{% block css %}
<style>
    .ok {
        color: green;
    }

    .no {
        color: red;
    }
</style>
{% endblock css %}

{% block content %}
<div class="page-header">
    <h2>
        Lista de Produtos
        <span class="pull-right">
            <a href="{% url 'produto:produto_add' %}">
                <button type="button" class="btn btn-primary">
                    <span class="fa fa-plus"></span>Adicionar
                </button>
            </a>
        </span>
    </h2>

    {% if object_list %}

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Importado</th>
                <th>NCM</th>
                <th>Produto</th>
                <th>Preço</th>
                <th class="text-center">Estoque</th>
                <th class="text-center">Estoque mínimo</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr>
                <td>
                    {% if object.importado %}
                    <i class="fa fa-check-circle ok"></i>
                    {% else %}
                    <i class="fa fa-minus-circle no"></i>
                    {% endif %}
                </td>
                <td>{{ object.ncm }}</td>
                <td>
                    <a href="{{ object.get_absolute_url }}">{{ object.produto }}</a>
                </td>
                <td>R$ <span class="pull-right">{{ object.preco }}</span></td>
                <td class="text-center">{{ object.estoque }}</td>
                <td class="text-center">{{ object.estoque_minimo }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p class="alert alert-warning">Sem itens na lista</p>
    {% endif %}
</div>
{% endblock content %}